### get user
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJGYWphciBNLiBIYW1rYSIsImVtYWlsIjoiZmFqYXJAZ21haWwuY29tIiwiaWF0IjoxNjQ5OTQwNTQxLCJleHAiOjE2NDk5NDA1NTZ9.eiB_W7G_M0yV24YJzXK27NWRT9hma3rGXBq1i3eJ1j0

### register user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fajar M. Hamka",
    "email": "fajar@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "fajar@gmail.com",
    "password": "123456"
}

### Minta token
GET http://localhost:5000/token

### Logout
DELETE http://localhost:5000/logout
