GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJGYWphciBNLiBIYW1rYSIsImVtYWlsIjoiZmFqYXJAZ21haWwuY29tIiwiaWF0IjoxNjQ5OTM5MDA0LCJleHAiOjE2NDk5MzkwMjR9.ZpP-CYCjc0-KDuofKv3JBTD3Wng_7xoSOi2OgI_wf_M

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fajar M. Hamka",
    "email": "fajar@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "fajar@gmail.com",
    "password": "123456"
}